# Generated by Django 2.2.6 on 2019-10-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('Doctor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_Name', models.CharField(max_length=25)),
                ('Specialization', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Email_ID', models.EmailField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Doctor Details',
                'db_table': 'doctors_details',
            },
        ),
        migrations.CreateModel(
            name='Patient_Appointment',
            fields=[
                ('Patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=100)),
                ('Email_ID', models.EmailField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=25)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Appointed_Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment_system.Doctor_Details')),
            ],
            options={
                'verbose_name_plural': 'Patient Appointment Details',
                'db_table': 'patient_appointment',
            },
        ),
    ]
